site_name: gd.docs
site_author: GD Programming
site_description: Documentation for Geometry Dash.

repo_name: gd-programming/gd.docs
repo_url: https://github.com/gd-programming/gd.docs

remote_branch: github-pages

watch:
  - docs

nav:
  - Index: "index.md"

  - Server:
    - Endpoints:
      - Comments:
        - Delete Level Comment: "server/endpoints/comments/delete_level_comment.md"
        - Delete User Comment: "server/endpoints/comments/delete_user_comment.md"
      - Friend Requests:
        - Accept Friend Request: "server/endpoints/friend_requests/accept_friend_request.md"
        - Delete Friend Request: "server/endpoints/friend_requests/delete_friend_request.md"
      - Levels:
        - Get Level: "server/endpoints/levels/get_level.md"
        - Delete Level: "server/endpoints/levels/delete_level.md"
      - Messages:
        - Delete Message: "server/endpoints/messages/delete_message.md"
        - Get Message: "server/endpoints/messages/get_message.md"
      - Users:
        - Block User: "server/endpoints/users/block_user.md"

    - Topics:
      - Error Codes: "server/topics/error_codes.md"
      - Secrets: "server/topics/secrets.md"
      - Songs: "server/topics/songs.md"
      - Versions: "server/topics/versions.md"

  - Client:
    - Topics:
      - Vault Codes: "client/topics/vault_codes.md"

  - Encoding:
    - AES: "encoding/aes.md"
    - Base64: "encoding/base64.md"
    - Checks: "encoding/checks.md"
    - Random String, UUID and UDID: "encoding/ids.md"
    - RobTop Encoding: "encoding/robtop.md"
    - Seeds: "encoding/seeds.md"
    - XOR: "encoding/xor.md"
    - ZIP: "encoding/zip.md"

  - Code of Conduct: "code_of_conduct.md"

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate

      primary: deep purple
      accent: light blue

      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default

      primary: deep orange
      accent: light blue

      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
